In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path

In [3]:
bucket_name = "dsan6000-sl2420"
prefix = "wikipedia-hourly/"

In [4]:
test_df = pd.read_parquet(
    f"s3://{bucket_name}/{prefix}20260901_040000.parquet"
)

test_df.head()

,datetime,$schema,meta,id,type,namespace,title,title_url,comment,timestamp,...,wiki,parsedcomment,log_id,log_type,log_action,log_params,log_action_comment,patrolled,file_ts,file_ts_str
0,2026-09-01 04:00:02,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Jake_O%...,2.063884e+09,edit,0,Jake O'Donnell,https://en.wikipedia.org/wiki/Jake_O%27Donnell,Fix dash,1788235202,...,enwiki,Fix dash,NaN,NaN,NaN,NaN,NaN,None,2026-09-01 04:00:00,20260901_040000
1,2026-09-01 04:00:02,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Beverid...,2.063884e+09,edit,0,Beveridge Award,https://en.wikipedia.org/wiki/Beveridge_Award,Add source,1788235202,...,enwiki,Add source,NaN,NaN,NaN,NaN,NaN,None,2026-09-01 04:00:00,20260901_040000
2,2026-09-01 04:00:01,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/1920_Un...,2.063884e+09,edit,0,1920 United States presidential election in Wa...,https://en.wikipedia.org/wiki/1920_United_Stat...,/* Counties that flipped from Democratic to Re...,1788235201,...,enwiki,"<span class=""autocomment""><a href=""/wiki/1920_...",NaN,NaN,NaN,NaN,NaN,None,2026-09-01 04:00:00,20260901_040000
3,2026-09-01 04:00:02,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/1987_Ae...,2.063884e+09,edit,0,1987 Aegean crisis,https://en.wikipedia.org/wiki/1987_Aegean_crisis,added a bit of context,1788235202,...,enwiki,added a bit of context,NaN,NaN,NaN,NaN,NaN,None,2026-09-01 04:00:00,20260901_040000
4,2026-09-01 04:00:03,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Marvin_...,2.063884e+09,edit,0,Marvin Schwäbe,https://en.wikipedia.org/wiki/Marvin_Schw%C3%A4be,NaN,1788235203,...,enwiki,NaN,NaN,NaN,NaN,NaN,NaN,None,2026-09-01 04:00:00,20260901_040000

In [5]:
import boto3

s3 = boto3.client("s3")

response = s3.list_objects_v2(
    Bucket=bucket_name,
    Prefix=prefix
)

parquet_keys = sorted([
    obj["Key"]
    for obj in response.get("Contents", [])
    if obj["Key"].endswith(".parquet")
])

print(f"Found {len(parquet_keys)} parquet files")
parquet_keys[:5]

Found 24 parquet files

['wikipedia-hourly/20260901_040000.parquet',
 'wikipedia-hourly/20260901_050000.parquet',
 'wikipedia-hourly/20260901_060000.parquet',
 'wikipedia-hourly/20260901_070000.parquet',
 'wikipedia-hourly/20260901_080000.parquet']

In [6]:
hourly_dfs = []

for key in parquet_keys:
    s3_uri = f"s3://{bucket_name}/{key}"
    print(f"Reading {s3_uri}")
    
    hour_df = pd.read_parquet(s3_uri)
    hourly_dfs.append(hour_df)

df = pd.concat(hourly_dfs, ignore_index=True)

print(df.shape)
df.head()

Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_040000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_050000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_060000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_070000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_080000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_090000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_100000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_110000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_120000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_130000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_140000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_150000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_160000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_170000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_180000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_190000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_200000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_210000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_220000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260901_230000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260902_000000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260902_010000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260902_020000.parquet
Reading s3://dsan6000-sl2420/wikipedia-hourly/20260902_030000.parquet
(119708, 29)

,datetime,$schema,meta,id,type,namespace,title,title_url,comment,timestamp,...,wiki,parsedcomment,log_id,log_type,log_action,log_params,log_action_comment,patrolled,file_ts,file_ts_str
0,2026-09-01 04:00:02,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Jake_O%...,2.063884e+09,edit,0,Jake O'Donnell,https://en.wikipedia.org/wiki/Jake_O%27Donnell,Fix dash,1788235202,...,enwiki,Fix dash,NaN,NaN,NaN,NaN,NaN,None,2026-09-01 04:00:00,20260901_040000
1,2026-09-01 04:00:02,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Beverid...,2.063884e+09,edit,0,Beveridge Award,https://en.wikipedia.org/wiki/Beveridge_Award,Add source,1788235202,...,enwiki,Add source,NaN,NaN,NaN,NaN,NaN,None,2026-09-01 04:00:00,20260901_040000
2,2026-09-01 04:00:01,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/1920_Un...,2.063884e+09,edit,0,1920 United States presidential election in Wa...,https://en.wikipedia.org/wiki/1920_United_Stat...,/* Counties that flipped from Democratic to Re...,1788235201,...,enwiki,"<span class=""autocomment""><a href=""/wiki/1920_...",NaN,NaN,NaN,NaN,NaN,None,2026-09-01 04:00:00,20260901_040000
3,2026-09-01 04:00:02,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/1987_Ae...,2.063884e+09,edit,0,1987 Aegean crisis,https://en.wikipedia.org/wiki/1987_Aegean_crisis,added a bit of context,1788235202,...,enwiki,added a bit of context,NaN,NaN,NaN,NaN,NaN,None,2026-09-01 04:00:00,20260901_040000
4,2026-09-01 04:00:03,/mediawiki/recentchange/1.0.0,{'uri': 'https://en.wikipedia.org/wiki/Marvin_...,2.063884e+09,edit,0,Marvin Schwäbe,https://en.wikipedia.org/wiki/Marvin_Schw%C3%A4be,NaN,1788235203,...,enwiki,NaN,NaN,NaN,NaN,NaN,NaN,None,2026-09-01 04:00:00,20260901_040000